/* Generated by Cython 0.29.1 */

#ifndef __PYX_HAVE__algorithm
#define __PYX_HAVE__algorithm


#ifndef __PYX_HAVE_API__algorithm

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *test(PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *add(PyObject *, PyObject *);
__PYX_EXTERN_C char add_with_type(int, int);

#endif /* !__PYX_HAVE_API__algorithm */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initalgorithm(void);
#else
PyMODINIT_FUNC PyInit_algorithm(void);
#endif

#endif /* !__PYX_HAVE__algorithm */
